.param Cbody = 0.7089u
.param Lbody = 158200
.param Rbody = 4.0348K
.param freq = 0.28201
.param Cgap =	1.3618u
.param Cwirebody = 0.7488u
.param Lwire = 708593
.param Rwire = 28.75K
.param q = 1
.param epsilon1 = 6.9*0.055263
.param RTline = 6k
.param phi = 5.3
.param Rin = 71.8330K
.param Cin = 49.8910u
.param amp = 10E-12
.param phase = 0.72*pi
.param sigdur = 5.1
.param Zin = 520K

;func fn_v(f) 1 - f  + f*ln(f)/6
;func get_f(E) pwr(q, 3)/(4*pi*epsilon1*pwr(phi, 2))*E

;func ifn(A, a, b, phi, vc, d, g) -1E-15*A*a*square(7*g*Efield(vc*1E+12, d))/phi*exp(-b*pwr(phi, 2/3)/(7*g*Efield(vc*1E+12, d))*fn_v(get_f(7*g*Efield(vc*1E+12, d))))
;func Efield(v,d) abs(max(v/d, 0))
;func is(A, alph, T, phi, vc, d, g) -1E-15*A*alph*square(T)*exp(min((-phi +0.5*sqrt((g*Efield(vc*1E+12, d)/(d*3.14*0.055263))/(0.8617u*T)), 0)))

.func gaussian_pulse(a, b, c, phase) a*exp(-square((time- b)/c)/2)*cos(2*pi*freq*(time - b)-phase)

;Values from fit over restricted Lbody and Rbody
;L_body = 0.1582 pH, R_body = 4.0348, c_body = 0.7089 aF
;c_gap = 1.3618 aF, cwb = 0.7488 aF, Rin = 71.8330, Cin= 49.8910 aF